site_name: RLO
theme:
  name: material
  palette:
    primary: green
    accent: orange
  font:
    text: Ubuntu
  icon:
    logo: material/robot-industrial-outline
  favicon: images/favicon-32x32.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
nav:
  - index.md
  - reinforcement_learning.md
  - Gymnasium:
    - Gymnasium/gym.md
    - Gymnasium/spaces.md
    - Gymnasium/creating_a_new_environment.md
    - Gymnasium/wrappers.md
  - PettingZoo:
    - PettingZoo/pettingzoo.md
    - PettingZoo/wrapping_pz_into_gym.md
  - concepts:
    - concepts/action_masking.md