site_name: RLO
theme:
  name: material
  palette:
    primary: green
    accent: orange
  font:
    text: Ubuntu
  icon:
    logo: material/robot-industrial-outline
  favicon: images/favicon-32x32.png
markdown_extensions:
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
nav:
  - index.md
  - reinforcement_learning.md
  - Gymnasium:
    - Gymnasium/gym.md
    - Gymnasium/spaces.md
    - Gymnasium/creating_a_new_environment.md
    - Gymnasium/wrappers.md
  - concepts:
    - concepts/action_masking.md